### ISSUE TITLE
Fits decompress to XISF

### ISSUE THREAD

**Issue by danieldh206** [sergio-dr/xisf#2]
Because of the growing file Fits file sizes more RICE compression is being used. I will keep trying to write my own Python code using Astropy but have difficulty getting it to batch convert into .xisf and not loose the header information. Can you make a fits2xisf.py that works with compressed Fits images?

Thank you,
Daniel

**Comment by sergio-dr** [comment]
Hi Daniel, sorry for the late answer. I'll try to have a look at this, can you provide a couple of RICE-compressed FITS files to work with?

**Comment by danieldh206** [comment]
Sergio, sorry for the really slow reply.  Here are 3 fits files with RICE compression
[SPA-2-CMOS_M101WITHSUPERNOVA2023IXF_rice_00002.zip](https://github.com/sergio-dr/xisf/files/12873637/SPA-2-CMOS_M101WITHSUPERNOVA2023IXF_rice_00002.zip)

**Comment by sergio-dr** [comment]
Thanks Daniel. So the problem you're encountering is to open these RICE-compressed FITS files with astropy.io.fits?

**Comment by sergio-dr** [comment]
Daniel, please try [fits2xisf.py](https://github.com/sergio-dr/xisf/blob/main/example/fits2xisf.py).
It seems to be working with your files. All FITS headers should be embedded on the XISF file, but beware that if you save the file with PixInsight, it may convert some of them to native XISF properties and **remove** them from the embedded FITS header, in particular the astrometric solution.

**Comment by danieldh206** [comment]
I will give the new fits2xisf.py a try in the next couple of days when I am back at my computer. Thank you for your time working on this.

**Comment by danieldh206** [comment]
[fits2xisf_multi.zip](https://github.com/sergio-dr/xisf/files/13329340/fits2xisf_multi.zip)
Did get it to write yet, but importing glob and multiprocessing this hacked together example makes it possible to convert a folder full of fits files using multiple processors. And sorry for adding the python as a zip file and not adding to github

**Comment by sergio-dr** [comment]
Hi @danieldh206, can this issue be closed? Thanks

**Comment by danieldh206** [comment]
You can close this issue. Thank you for your help.

**Comment by danieldh206** [comment]
Don't know if you noticed, but if you run decompress on an already uncompressed image, the image gets compressed. CompImageHDU automatically compresses with 'Rice_1' or decompresses. Daniel
